server:
  port: 8088
  
spring:
  application:
    name: cms-order
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///db_springcloud-cms?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  # rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

env:
  dev
